name: Build Teacher Client

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # CRITICAL: This downloads the uriparser and wil code needed for the build
        submodules: recursive 

    - name: Configure CMake
      run: cmake -S . -B build -A x64 -DURIPARSER_BUILD_DOCS=OFF -DURIPARSER_BUILD_TESTS=OFF -DURIPARSER_BUILD_TOOLS=OFF

    - name: Build with CMake
      run: cmake --build build --config Release
      
    - name: Upload Finished Client
      uses: actions/upload-artifact@v4
      with:
        name: Teacher-Client-EXE
        path: build/src/Release/